# Generated by Django 3.0.5 on 2020-07-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_username', models.CharField(max_length=30)),
                ('customer_phone', models.CharField(max_length=30)),
                ('lead_converted', models.IntegerField()),
                ('lead_category', models.CharField(max_length=30)),
                ('lead_isactive', models.BooleanField(default=True)),
            ],
        ),
    ]
